const ukCourierNames = [
    'Royal Mail',
    'DHL Express',
    'UPS',
    'FedEx',
    'Hermes',
    'DPD',
    'Parcelforce Worldwide',
    'TNT Express',
    'Yodel',
    'UK Mail',
    'DX (Group)',
    'CitySprint',
    'CollectPlus',
    'APC Overnight',
    'Whistl',
    'Interlink Express',
    'Palletways',
    'ArrowXL',
    'Tuffnells',
    'Nightline',
    'P2P Mailing',
    'InPost',
    'P4D (Parcel 4 Delivery)',
    'Palletforce',
    'Speedy Freight',
    'Asendia UK',
    'PostNord',
    'XDP Express',
    'GFS (Global Freight Solutions)',
    'Crossflight',
    'Swiss Post Solutions',
    'SkyNet Worldwide Express',
    'Nightfreight',
    'InXpress',
    'Hermesworld',
    'Royal Mail Parcels',
    'P2P TrakPak',
    'P2P Courier Services',
    'TG International',
    'UPS Mail Innovations',
    'DX Express',
    'Transglobal Express',
    'Despatch Bay',
    'Hermes Parcelnet',
    'Ipostparcels',
    'Mondial Relay',
    'Yodel Direct',
    'Hermes Europe GmbH',
    'Hermes Logistik Gruppe Deutschland',
    'Asendia USA',
    'P4D',
    'Hermes UK',
    'PacketPort',
    'FedEx Freight',
    'DPDgroup UK',
    'DPD Local',
    'Yodel Xpress',
];

export default ukCourierNames;
