[
  {
    category: 'new in',
    products: [
      {
        id: 'e75c4e77-ced2-40b1-b841-87047f8a26e8',
        title: 'River Island short sleeve t-shirt in white',
        images: [
          'https://images.asos-media.com/products/river-island-short-sleeve-t-shirt-in-white/205185905-4?$n_640w$&wid=513&fit=constrain',
          'https://images.asos-media.com/products/river-island-short-sleeve-t-shirt-in-white/205185905-1-white?$n_640w$&wid=513&fit=constrain',
          'https://images.asos-media.com/products/river-island-short-sleeve-t-shirt-in-white/205185905-2?$n_640w$&wid=513&fit=constrain',
          'https://images.asos-media.com/products/river-island-short-sleeve-t-shirt-in-white/205185905-3?$n_640w$&wid=513&fit=constrain',
          'https://images.asos-media.com/products/river-island-short-sleeve-t-shirt-in-white/205185905-4?$n_640w$&wid=513&fit=constrain',
        ],
        price: 15,
        sizes: [
          { size: 'S - Chest 35-37', stock: 3 },
          { size: 'L - Chest 41-43', stock: 5 },
          { size: 'XL - Chest 44-46', stock: 16 },
          { size: 'XXL - Chest 47-49', stock: 17 },
        ],
        detail: [
          'Talk about a wardrobe staple',
          'Plain design',
          'Crew neck',
          'Raglan sleeves',
          'Regular fit',
        ],
      },
    ],
  },
  {
    category: 'clothing',
    products: [
      {
        id: '7fc3eb3f-3e8c-4e77-a29c-5c3edada5a5b',
        title:
          'ASOS DESIGN oversized t-shirt in white with New York back print',
        images: [
          'https://images.asos-media.com/products/asos-design-oversized-t-shirt-in-white-with-new-york-back-print/204257420-5?$n_640w$&wid=513&fit=constrain',
          'https://images.asos-media.com/products/asos-design-oversized-t-shirt-in-white-with-new-york-back-print/204257420-1-white?$n_640w$&wid=513&fit=constrain',
          'https://images.asos-media.com/products/asos-design-oversized-t-shirt-in-white-with-new-york-back-print/204257420-2?$n_640w$&wid=513&fit=constrain',
          'https://images.asos-media.com/products/asos-design-oversized-t-shirt-in-white-with-new-york-back-print/204257420-3?$n_640w$&wid=513&fit=constrain',
          'https://images.asos-media.com/products/asos-design-oversized-t-shirt-in-white-with-new-york-back-print/204257420-4?$n_640w$&wid=513&fit=constrain',
          'https://images.asos-media.com/products/asos-design-oversized-t-shirt-in-white-with-new-york-back-print/204257420-5?$n_640w$&wid=513&fit=constrain',
        ],
        price: null,
        sizes: [
          { size: '2XS - Chest 34', stock: 16 },
          { size: 'XS - Chest 36', stock: 1 },
          { size: 'S - Chest 38', stock: 0 },
          { size: 'M - Chest 40', stock: 5 },
          { size: 'L - Chest 42', stock: 6 },
          { size: 'XL - Chest 44', stock: 4 },
          { size: '2XL - Chest 46-48', stock: 18 },
        ],
        detail: [
          'On-the-daily dressing',
          'Crew neck',
          'Drop shoulders',
          'Text print to back',
          'Oversized fit',
        ],
      },
    ],
  },
  {
    category: 'shoes',
    products: [
      {
        id: '2a66fc7d-8a49-4d30-adb4-9e422c54e65a',
        title: 'Converse Chuck Taylor All Star Hi unisex trainers in black',
        images: [
          'https://images.asos-media.com/products/converse-chuck-taylor-all-star-hi-unisex-trainers-in-black/201956357-4?$n_640w$&wid=513&fit=constrain',
          'https://images.asos-media.com/products/converse-chuck-taylor-all-star-hi-unisex-trainers-in-black/201956357-1-black?$n_640w$&wid=513&fit=constrain',
          'https://images.asos-media.com/products/converse-chuck-taylor-all-star-hi-unisex-trainers-in-black/201956357-2?$n_640w$&wid=513&fit=constrain',
          'https://images.asos-media.com/products/converse-chuck-taylor-all-star-hi-unisex-trainers-in-black/201956357-3?$n_640w$&wid=513&fit=constrain',
          'https://images.asos-media.com/products/converse-chuck-taylor-all-star-hi-unisex-trainers-in-black/201956357-4?$n_640w$&wid=513&fit=constrain',
        ],
        price: 60,
        sizes: [
          { size: 'UK 3', stock: 1 },
          { size: 'UK 3.5', stock: 17 },
          { size: 'UK 4', stock: 10 },
          { size: 'UK 4.5', stock: 7 },
          { size: 'UK 5 ', stock: 10 },
          { size: 'UK 5.5', stock: 17 },
          { size: 'UK 6 ', stock: 5 },
          { size: 'UK 6.5', stock: 16 },
          { size: 'UK 7', stock: 1 },
          { size: 'UK 7.5', stock: 1 },
          { size: 'UK 8', stock: 13 },
          { size: 'UK 8.5', stock: 10 },
          { size: 'UK 9', stock: 6 },
          { size: 'UK 9.5', stock: 5 },
          { size: 'UK 10', stock: 8 },
          { size: 'UK 10.5', stock: 0 },
          { size: 'UK 11', stock: 16 },
          { size: 'UK 11.5', stock: 1 },
          { size: 'UK 12', stock: 2 },
          { size: 'UK 13', stock: 17 },
        ],
        detail: [
          'Your casualwear companions',
          'High-top design',
          'Lace-up fastening',
          'Signature Converse All Star branding',
          'Breathable eyelet vents to inner foot',
          'Vulcanised rubber toe cap and outsole',
          'Archival rubber taping',
          'Geometric grip tread',
          'Unisex style',
        ],
      },
    ],
  },
  { category: 'accessories', products: [[{ size: 'One Size', stock: 11 }]] },
  {
    category: 'Sportswear',
    products: [
      {
        id: '237385aa-dc6f-4747-b720-8de9a7a78cf3',
        title: 'New Balance 530 trainers in white and grey',
        images: [
          'https://images.asos-media.com/products/new-balance-530-trainers-in-white-and-grey/204470705-4?$n_640w$&wid=513&fit=constrain',
          'https://images.asos-media.com/products/new-balance-530-trainers-in-white-and-grey/204470705-1-white?$n_640w$&wid=513&fit=constrain',
          'https://images.asos-media.com/products/new-balance-530-trainers-in-white-and-grey/204470705-2?$n_640w$&wid=513&fit=constrain',
          'https://images.asos-media.com/products/new-balance-530-trainers-in-white-and-grey/204470705-3?$n_640w$&wid=513&fit=constrain',
          'https://images.asos-media.com/products/new-balance-530-trainers-in-white-and-grey/204470705-4?$n_640w$&wid=513&fit=constrain',
        ],
        price: 100,
        sizes: [
          { size: 'UK 3.5', stock: 15 },
          { size: 'UK 4', stock: 7 },
          { size: 'UK 4.5', stock: 1 },
          { size: 'UK 5', stock: 2 },
          { size: 'UK 5.5', stock: 1 },
          { size: 'UK 6', stock: 15 },
          { size: 'UK 6.5', stock: 10 },
          { size: 'UK 7', stock: 10 },
          { size: 'UK 7.5', stock: 8 },
          { size: 'UK 8', stock: 18 },
          { size: 'UK 8.5', stock: 9 },
          { size: 'UK 9', stock: 8 },
          { size: 'UK 9.5', stock: 6 },
          { size: 'UK 10', stock: 7 },
          { size: 'UK 10.5', stock: 2 },
          { size: 'UK 11.5', stock: 19 },
          { size: 'UK 12.5 ', stock: 5 },
        ],
        detail: [
          'Your casualwear companions',
          'Low-profile design',
          'Pull tab for easy entry',
          'Lace-up fastening',
          'Padded tongue and cuff',
          'Signature New Balance branding',
          'Perforated for ventilation',
          'ABZORB midsole provides responsive, energy-returning cushioning',
          'Durable rubber outsole',
          'Textured grip tread',
        ],
      },
    ],
  },
  {
    category: 'Summer',
    products: [
      {
        id: 'e41ed788-03ce-443f-9b95-15333c6d64bc',
        title: 'ASOS DESIGN t-shirt with crew neck in white',
        images: [
          'https://images.asos-media.com/products/asos-design-t-shirt-with-crew-neck-in-white/204188226-4?$n_640w$&wid=513&fit=constrain',
          'https://images.asos-media.com/products/asos-design-t-shirt-with-crew-neck-in-white/204188226-1-white?$n_640w$&wid=513&fit=constrain',
          'https://images.asos-media.com/products/asos-design-t-shirt-with-crew-neck-in-white/204188226-2?$n_640w$&wid=513&fit=constrain',
          'https://images.asos-media.com/products/asos-design-t-shirt-with-crew-neck-in-white/204188226-3?$n_640w$&wid=513&fit=constrain',
          'https://images.asos-media.com/products/asos-design-t-shirt-with-crew-neck-in-white/204188226-4?$n_640w$&wid=513&fit=constrain',
        ],
        price: 8,
        sizes: [
          { size: '2XS - Chest 34 ', stock: 3 },
          { size: 'XS - Chest 36', stock: 18 },
          { size: 'S - Chest 38 ', stock: 14 },
          { size: 'S Long - Chest 38 Long ', stock: 6 },
          { size: 'M - Chest 40', stock: 0 },
          { size: 'M Long - Chest 40 Long ', stock: 14 },
          { size: 'L - Chest 42', stock: 5 },
          { size: 'L Long - Chest 42 Long ', stock: 0 },
          { size: 'XL - Chest 44', stock: 5 },
          { size: 'XL Long - Chest 44 Long ', stock: 15 },
          { size: '2XL - Chest 46-48', stock: 5 },
          { size: '2XL Long - Chest 46-48 Long ', stock: 18 },
          { size: '3XL - Chest 50-52', stock: 3 },
          { size: '4XL - Chest 54-56', stock: 9 },
        ],
        detail: [
          'File under: basics',
          'Crew neck',
          'Short sleeves',
          'Regular fit',
        ],
      },
    ],
  },
  {
    category: 'Brands',
    products: [
      {
        id: 'dd10002f-8555-4446-b5be-12a38a981375',
        title: 'Topman long sleeve check shirt in blue',
        images: [
          'https://images.asos-media.com/products/topman-long-sleeve-check-shirt-in-blue/204386804-4?$n_640w$&wid=513&fit=constrain',
          'https://images.asos-media.com/products/topman-long-sleeve-check-shirt-in-blue/204386804-1-green?$n_640w$&wid=513&fit=constrain',
          'https://images.asos-media.com/products/topman-long-sleeve-check-shirt-in-blue/204386804-2?$n_640w$&wid=513&fit=constrain',
          'https://images.asos-media.com/products/topman-long-sleeve-check-shirt-in-blue/204386804-3?$n_640w$&wid=513&fit=constrain',
          'https://images.asos-media.com/products/topman-long-sleeve-check-shirt-in-blue/204386804-4?$n_640w$&wid=513&fit=constrain',
        ],
        price: 34,
        sizes: [
          { size: 'XS - Chest 36', stock: 12 },
          { size: 'S - Chest 38', stock: 6 },
          { size: 'M - Chest 40', stock: 0 },
          { size: 'L - Chest 42', stock: 19 },
          { size: 'XL - Chest 44', stock: 9 },
          { size: '2XL - Chest 46-48', stock: 0 },
        ],
        detail: [
          'Welcome to the next phase of Topman',
          'Spread collar',
          'Button placket',
          'Chest pocket',
          'Regular fit',
        ],
      },
    ],
  },
  {
    category: 'topman',
    products: [
      {
        id: 'cdd75165-d8a0-463f-98fd-867f409a15e1',
        title: 'Topman long sleeve check shirt in blue',
        images: [
          'https://images.asos-media.com/products/topman-long-sleeve-check-shirt-in-blue/204386804-4?$n_640w$&wid=513&fit=constrain',
          'https://images.asos-media.com/products/topman-long-sleeve-check-shirt-in-blue/204386804-1-green?$n_640w$&wid=513&fit=constrain',
          'https://images.asos-media.com/products/topman-long-sleeve-check-shirt-in-blue/204386804-2?$n_640w$&wid=513&fit=constrain',
          'https://images.asos-media.com/products/topman-long-sleeve-check-shirt-in-blue/204386804-3?$n_640w$&wid=513&fit=constrain',
          'https://images.asos-media.com/products/topman-long-sleeve-check-shirt-in-blue/204386804-4?$n_640w$&wid=513&fit=constrain',
        ],
        price: 34,
        sizes: [
          { size: 'XS - Chest 36', stock: 5 },
          { size: 'S - Chest 38', stock: 10 },
          { size: 'M - Chest 40', stock: 0 },
          { size: 'L - Chest 42', stock: 16 },
          { size: 'XL - Chest 44', stock: 12 },
          { size: '2XL - Chest 46-48', stock: 11 },
        ],
        detail: [
          'Welcome to the next phase of Topman',
          'Spread collar',
          'Button placket',
          'Chest pocket',
          'Regular fit',
        ],
      },
    ],
  },
  { category: 'Marketplace', products: [[{ size: 'L', stock: 18 }]] },
  {
    category: 'outlet',
    products: [
      {
        id: '94b1d46a-6416-4548-94b0-9c2fd7356f6e',
        title: 'French Connection lined funnel neck mac jacket in black',
        images: [
          'https://images.asos-media.com/products/french-connection-lined-funnel-neck-mac-jacket-in-black/202769312-4?$n_640w$&wid=513&fit=constrain',
          'https://images.asos-media.com/products/french-connection-lined-funnel-neck-mac-jacket-in-black/202769312-1-black?$n_640w$&wid=513&fit=constrain',
          'https://images.asos-media.com/products/french-connection-lined-funnel-neck-mac-jacket-in-black/202769312-2?$n_640w$&wid=513&fit=constrain',
          'https://images.asos-media.com/products/french-connection-lined-funnel-neck-mac-jacket-in-black/202769312-3?$n_640w$&wid=513&fit=constrain',
          'https://images.asos-media.com/products/french-connection-lined-funnel-neck-mac-jacket-in-black/202769312-4?$n_640w$&wid=513&fit=constrain',
        ],
        price: null,
        sizes: [
          { size: 'XS - Chest 34', stock: 15 },
          { size: 'S - Chest 36', stock: 14 },
          { size: 'M - Chest 38', stock: 9 },
          { size: 'L - Chest 40', stock: 2 },
          { size: 'XL - Chest 42', stock: 0 },
        ],
        detail: [
          'Mid-season layering',
          'High collar',
          'Button placket',
          'Side pockets',
          'Regular fit',
        ],
      },
    ],
  },
];
