name: Deploy Glamo Frontend

on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Login to docker hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Create .env file 
        run: |
          echo -e "${{ secrets.FRONTEND_ENV_FILE }}" > .env
          cat .env  # Optional: Check the contents of the .env file
      - name: Build Docker Image
        run: docker build -t kevinjean/glamo-frontend-app ./client
      - name: Publish Image to docker hub
        run: docker push kevinjean/glamo-frontend-app:latest

  deploy:
    needs: build
    runs-on: frontend-runner
    steps:
      - name: Pull image from docker hub
        run: docker pull kevinjean/glamo-frontend-app:latest 
      - name: Stop container
        run: | 
          docker stop glamo-frontend-container || true
      - name: Delete old container
        run: | 
          docker rm -f glamo-frontend-container || true
      - name: Run Docker Container
        run: docker run -d -p 80:80 --name glamo-frontend-container kevinjean/glamo-frontend-app:latest
        
