name: Deploy Glamo Frontend

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Login to docker hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build Docker Image
        run: docker build -t kevinjean/glamo-frontend-app ./client
      - name: Publish Image to docker hub
        run: docker push kevinjean/glamo-frontend-app:latest

  deploy:
    needs: build
    runs-on: frontend-runner
    steps:
        - name: Create .env file
        run: echo "${{ secrets.ENV_FILE }}" > .env
      - name: Pull image from docker hub
        run: docker pull kevinjean/glamo-frontend-app:latest
      - name: Delete old container
        run: docker rm -f glamo-frontend-container
      - name: Run Docker Container
        run: docker run -d -p --env-file .env 3000:3000 --name glamo-frontend-container kevinjean/glamo-frontend-app:latest
