name: Deploy Glamo Backend

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Login to docker hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Remove old Docker images (optional)
        run: |
          docker image prune -a -f
          docker container prune -f
      - name: Create .env file
        run: |
          echo "${{ secrets.ENV_FILE }}" > .env
      - name: Build Docker Image
        run: docker build --env-file .env -t kevinjean/glamo-backend-app ./server
      - name: Publish Image to docker hub
        run: docker push kevinjean/glamo-backend-app:latest

  deploy:
    needs: build
    runs-on: backend-runner
    steps:
      - name: Pull image from docker hub
        run: docker pull kevinjean/glamo-backend-app:latest
      - name: Delete old container
        run: docker rm -f glamo-backend-container
      - name: Remove any existing containers (optional)
        run: |
          docker rm -f glamo-backend-container || true
          docker container prune -f
          docker image prune -a -f
      - name: Run Docker Container
        run: docker run -d -p 3000:3000 --name glamo-backend-container -e URL='${{ secrets.URL }}' kevinjean/glamo-backend-app
